@baseUrl = http://localhost:3333

# health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get all rooms
#@name getRooms
GET {{baseUrl}}/rooms

###

# Create a room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Room 1",
    "description": "Room 1 description"
}

###

@roomId = e7b2874d-f52c-4b14-9b2e-ee8ca30b83f6
//{{createRoom.response.body.$.roomId}}

###

# Create a question
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "What is the capital of France?"
}

###
# Get questions for a room
#@name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/6f05315b-1442-4bfa-af46-cf39d951f59e/questions
Content-Type: application/json

{
  "question": "O que é Vue.js e a sua diferença em relação ao Angular?"
}

